global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'product-service'
    static_configs:
      - targets: ['product-service:3001']
    metrics_path: '/metrics'
    scrape_interval: 15s

  - job_name: 'order-service'
    static_configs:
      - targets: ['order-service:3002']
    metrics_path: '/metrics'
    scrape_interval: 15s

  - job_name: 'search-service'
    static_configs:
      - targets: ['search-service:3003']
    metrics_path: '/metrics'
    scrape_interval: 15s

  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:3004']
    metrics_path: '/metrics'
    scrape_interval: 15s

  - job_name: 'notification-service'
    static_configs:
      - targets: ['notification-service:3005']
    metrics_path: '/metrics'
    scrape_interval: 15s

  - job_name: 'analytics-service'
    static_configs:
      - targets: ['analytics-service:3006']
    metrics_path: '/metrics'
    scrape_interval: 15s

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']
    metrics_path: '/metrics'
    scrape_interval: 15s

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:9187']
    metrics_path: '/metrics'
    scrape_interval: 15s

  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb:9216']
    metrics_path: '/metrics'
    scrape_interval: 15s

  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['elasticsearch:9200']
    metrics_path: '/_prometheus/metrics'
    scrape_interval: 15s

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:9121']
    metrics_path: '/metrics'
    scrape_interval: 15s